const DISPOSABLE_DOMAINS = new Set([
  "mailinator.com","mailinator.net","mailinator.org","trashmail.com","trashmail.me",
  "trashmail.net","trashmail.org","trashmail.at","trashmail.io","trashmail.xyz",
  "guerrillamail.com","guerrillamail.net","guerrillamail.org","guerrillamail.biz",
  "guerrillamail.de","guerrillamailblock.com","grr.la","sharklasers.com","spam4.me",
  "yopmail.com","yopmail.fr","cool.fr.nf","jetable.fr.nf","nospam.ze.tc",
  "nomail.xl.cx","mega.zik.dj","speed.1s.fr","courriel.fr.nf","moncourrier.fr.nf",
  "monemail.fr.nf","monmail.fr.nf","10minutemail.com","10minutemail.net","10minutemail.org",
  "10minutemail.de","10minutemail.info","10minutemail.co.uk","throwam.com","throam.com",
  "throwm.me","throwaway.email","fakeinbox.com","maildrop.cc","dispostable.com",
  "mailnull.com","spamgourmet.com","spamgourmet.net","spamgourmet.org","spamex.com",
  "getairmail.com","filzmail.com","mytemp.email","tempr.email","discard.email",
  "getnada.com","mailnesia.com","mintemail.com","tempmail.com","tempmail.net",
  "tempmail.org","tempmail.de","tempmail.us","tempmail.eu","temp-mail.org",
  "temp-mail.ru","temp-mail.io","tempemail.com","tempemail.net","temp.emeraldwebmail.com",
  "tempinbox.com","tempinbox.co.uk","temporaryemail.net","temporaryemail.us",
  "temporaryinbox.com","temporarymail.org","tempthe.net","tempalias.com","tempail.com",
  "e4ward.com","emailondeck.com","mailf5.com","mailme24.com","mailmetrash.com",
  "mailmoat.com","mailnew.com","mailscrap.com","mailzilla.org","mailexpire.com",
  "spamhole.com","spamify.com","spaml.com","spaml.de","spam.la","spam.su",
  "spamcero.com","spamcon.org","spamday.com","spamdead.com","spamfree.eu",
  "spamoff.de","spamspot.com","spamstack.net","spamthis.co.uk","spammotel.com",
  "spambox.info","spambox.us","spamcannon.com","spamcannon.net","nobulk.com",
  "nospamfor.us","nospammail.net","no-spam.ws","trashcanmail.com","trashdevil.com",
  "trashdevil.net","trash2009.com","trash-mail.at","trash-mail.cf","trash-mail.ga",
  "trash-mail.io","dayrep.com","binkmail.com","bobmail.info","chogmail.com",
  "dingbone.com","dump-email.info","emz.net","fakemails.org","frapmail.com",
  "get2mail.fr","getonemail.com","hulapla.de","ilkpostam.com","kurzepost.de",
  "letthemeatspam.com","mailexpire.com","makemetheking.com","meinspamschutz.de",
  "mt2009.com","mymail-in.net","netzidiot.de","onewaymail.com","pjjkp.com",
  "privacy.net","privatemail.net","proxymail.eu","putthisinyourspamdatabase.com",
  "recursor.net","riku.me","safetymail.info","safetypost.de","sandelf.de",
  "schafmail.de","sendspamhere.com","shieldedmail.com","shitmail.me","shortmail.net",
  "sibmail.com","skeefmail.com","slopsbox.com","slushmail.com","smapfree24.com",
  "smapfree24.de","smapfree24.eu","smapfree24.info","smapfree24.net","smapfree24.org",
  "sneakemail.com","snkmail.com","sofimail.com","sofort-mail.de","soggymail.com",
  "spoofmail.de","stuffmail.de","super-auswahl.de","supergreatmail.com","suremail.info",
  "tafmail.com","teleworm.com","tempe-mail.com","tempemail.biz","tempemail.co.za",
  "tempimbox.com","tempimbox.co.uk","throwam.com","tilien.com","tittbit.in",
  "tmailinator.com","toiea.com","tradermail.info","trash-amil.com","twinmail.de",
  "tyldd.com","uggsrock.com","umail.net","uroid.com","vmail.me","webemail.me",
  "webm4il.info","wegwerfadresse.de","wegwerfmail.de","wegwerfmail.net","wegwerfmail.org",
  "willhackforfood.biz","willselfdestruct.com","wmail.cf","writeme.us","wronghead.com",
  "wuzupmail.net","xagloo.com","xemaps.com","xents.com","xmaily.com","xoxy.net",
  "xyzfree.net","yapped.net","ypmail.webarnak.fr.eu.org","yuurok.com",
  "zehnminutenmail.de","zoemail.org","zomg.info","zweitespam.net","zzrgg.com",
  "owlpic.com","nwytg.com","drdrb.net","drdrb.com","smashmail.de","spaeriously.com",
  "spamfree24.de","spamfree24.eu","spamfree24.info","spamfree24.net","spamfree24.org",
  "spamgoes.in","spamherelots.com","spamhereplease.com","inoutmail.eu","inoutmail.de",
  "inoutmail.info","inoutmail.net","instant-mail.de","ispuntheweb.com",
  "jetable.com","jetable.net","jetable.org","jnxjn.com","jourrapide.com",
  "jumonji.tk","kasmail.com","kaspop.com","killmail.com","killmail.net",
  "klassmaster.com","klassmaster.net","lol.ovpn.to","lolfreak.net",
  "lookugly.com","lortemail.dk","lucky.romail.com","lukemail.com","lukop.dk",
  "m21.cc","mail1a.de","mail21.cc","mail2rss.org","mail333.com",
  "mailbidon.com","mailbiz.biz","mailblocks.com","mailbucket.org","mailc.net",
  "mailcat.biz","mailcatch.com","mailche.com","mailchop.com","mailcker.com",
  "mailcx.cf","mailcx.ga","mailcx.gq","mailcx.ml","mailcx.tk",
  "mailde.de","mailde.info","maildrop.cf","maildu.de","mailempty.com",
  "mailerino.com","mailfall.com","mailfs.com","mailguard.me","mailhazard.com",
  "mailimate.com","mailin8r.com","mailinater.com","mailite.com","mailme.ir",
  "mailme.lv","mailnew.com","mailonto.com","mailpick.biz","mailproxsy.com",
  "mailpuppy.com","mailquack.com","mailrock.biz","mailseal.de","mailshell.com",
  "mailsiphon.com","mailslapping.com","mailslite.com","mailsucker.net","mailtemp.info",
  "mailtome.de","mailtothis.com","mailueberfall.de","mailup.net","mailwithyou.com",
  "mailworks.org","mailzilla.com","makemetheking.com","malahov.de",
  "manifestgoo.com","mbx.cc","mega.zik.dj","meinspamschutz.de","meltmail.com",
  "messagebeamer.de","mezimages.net","mierdamail.com","migmail.net","migmail.pl",
  "migumail.com","millionaireintraining.com","mjukglass.nu","moaktmail.com",
  "mobi.web.id","mobileninja.co.uk","moburl.com","moncierge.be",
]);

const ROLE_PREFIXES = new Set([
  "admin","support","sales","info","billing","contact","help","noreply","no-reply",
  "postmaster","webmaster","marketing","office","team","hello","abuse","security",
  "newsletter","mail","jobs","careers","hr","finance","legal","press","media",
  "service","services","ops","operations","dev","developer","api","bot","robot",
  "notification","notifications","alerts","donotreply","do-not-reply","bounce",
  "mailer","smtp","imap","pop","root","hostmaster","usenet","news","uucp",
  "ftp","www","web","email","enquiries","enquiry","inquiry","inquiries",
]);

export function isDisposable(domain: string): boolean {
  return DISPOSABLE_DOMAINS.has(domain.toLowerCase());
}

export function isRoleBased(local: string): boolean {
  return ROLE_PREFIXES.has(local.toLowerCase());
}
